### ISSUE TITLE
ImportError: No module named rpy

### ISSUE THREAD

**Issue by tnabtaf** [galaxyproject/ansible-cloudman-image#20]
The "Summary Statistics" tool is getting this error in a 16.03 Image/16.04 flavor CloudMan instance:

```
Traceback (most recent call last):
  File "/mnt/galaxy/galaxy-app/tools/stats/gsummary.py", line 10, in <module>
    from rpy import BASIC_CONVERSION, NO_CONVERSION, r, RException, set_default_mode
ImportError: No module named rpy
```

This is not a critical bug for me.  I'm generating stats from a 2 column dataset, using the 2nd column, which is all  integers

**Comment by afgane** [comment]
@nturaga Would you be interested in taking a look at this?

**Comment by nturaga** [comment]
@afgane yes.

**Comment by Thyra** [comment]
I'm still having this problem on a fresh install on MacOS (Galaxy release 19.09). My python version is 2.7.16 and MacOS version is 10.15.1

```
Traceback (most recent call last):
  File "/Users/***/Desktop/galaxy/tools/stats/gsummary.py", line 11, in <module>
    from rpy import BASIC_CONVERSION, NO_CONVERSION, r, RException, set_default_mode
ImportError: No module named rpy
```
