### ISSUE TITLE
Precompute some HISAT2 indexes 

### ISSUE THREAD

**Issue by tnabtaf** [galaxyproject/ansible-cloudman-image#21]
I've switched from using Tophat2 to using HISAT2 in workshops.  The 16.03 Image/16.04 flavor CloudMan instance does not have any precomputing HISAT2 indexes.  

The one I need most is hg38, but I suggest just building the same set that is built for Bowtie.

Note: the instance does have the HISAT2 index data manager on it.  Which means there is an easy workaround for anyone who knows how to use data managers.

**Comment by afgane** [comment]
It's been a while that this has been open as we moved to CVMFS-based references since anyhow so closing this.
