### ISSUE TITLE
Download MPI failing

### ISSUE THREAD

**Issue by alexjsmac** [galaxyproject/ansible-cloudman-image#8]
Hello, so I am trying to build a Galaxy on the Cloud platform but when I execute the cloudman image build it always fails when it attempts to download MPI. The error states that an SSL certificate does not belong to www.open-mpi.org. I am using Ansible 1.9.2. To avoid this I have skipped the MPI step by setting the cm_install_mpi variable to no and the rest of the build works. But is MPI something that is vital to the final product?

**Comment by afgane** [comment]
Not at the moment but there will hopefully be MPI-based tools coming online in the near future so we added it into the image. 

I changed the download URL from `https` to just `http` to avoid this problem though (see 45291761b3945710c8529bf5ee2987f465d389e1).

Thanks for letting us know.

**Comment by alexjsmac** [comment]
Sounds good thanks!
